language: go
go:
  - 1.11

services:
  - postgres

env:
  - DB_TEST=postgres://postgres@localhost:5432/postgres?sslmode=disable
  - GO111MODULE=on


script:
  - make test

after_script:
  - make docker-build
  - make docker-push