language: go
go:
- 1.11
services:
- postgres
script:
- go get github.com/mattn/goveralls
- make coverage
deploy:
  - provider: script
    script: make docker-build && make docker-push
    on:
      tags: true
      all_branches: true
